_wandb:
    value:
        cli_version: 0.27.2
        e:
            z80gghwm7gi7pyjbqsnl8wjryp8x61xl:
                args:
                    - --data_dir
                    - C:\Users\sayan\mehthab\kg-peft\~kg-peft\data\bc5cdr\CDR_Data
                codePath: zero_shot_baseline.py
                codePathLocal: zero_shot_baseline.py
                cpu_count: 8
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "509722226688"
                        used: "419025080320"
                email: mehthabunstoppable@gmail.com
                executable: C:\Users\sayan\miniconda3\envs\kgpeft311\python.exe
                gpu: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                      uuid: GPU-87fc8de5-79f5-6e4f-e614-73d712a7b897
                host: Sayanth
                memory:
                    total: "16873545728"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\sayan\mehthab\zero_shot_baseline.py
                python: CPython 3.11.15
                root: C:\Users\sayan\mehthab
                startedAt: "2026-06-13T12:30:31.868943Z"
                writerId: z80gghwm7gi7pyjbqsnl8wjryp8x61xl
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 11
                - 33
                - 49
            "2":
                - 1
                - 11
                - 33
                - 49
                - 71
            "3":
                - 13
                - 16
            "4": 3.11.15
            "5": 0.27.2
            "6": 4.41.0
            "8":
                - 3
            "12": 0.27.2
            "13": windows-amd64
dataset:
    value: BC5CDR
max_samples:
    value: 50
mode:
    value: zero-shot
model:
    value: BioMistral/BioMistral-7B
task:
    value: NER
